name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dast:
    name: DAST Analysis (OWASP ZAP)
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      issues: write
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask App (for scanning)
        run: |
          source venv/bin/activate
          nohup python app.py &
          sleep 5
        env:
          FLASK_ENV: testing

      - name: Fix Permissions for ZAP
        run: chmod 777 ${{ github.workspace }}

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "http://127.0.0.1:8000"
          fail_action: false
          issue_title: "ZAP DAST Scan Report"
          artifact_name: zap-results

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-html-report
          path: report_html.html

  deploy:
    runs-on: self-hosted
    needs: dast
    if: ${{ always() }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Delete Flask App if existing
        run: |
          pm2 delete flask-app || true

      - name: Run Flask App
        run: |
          pm2 start app.py --name flask-app --interpreter venv/bin/python
          pm2 save